name: CI

on:
  push:
    branches: [ feat/ci ]
  pull_request:
    branches: [ feat/ci ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: npm install miniu && node ./miniu-sdk/upload.js

